version: "3"
services:
  jupyter:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      PYTHONPATH: /workspace
      JUPYTER_TOKEN: dev
    volumes:
      - ..:/workspace
      - ./jupyter_server_config.py:/etc/jupyter/jupyter_server_config.py:ro
    ports:
      - 8888:8888
    command: sleep infinity
